layout_spectrum: 0.4123129
color:
  saturation: 0.01767064
  lightness: 0.9818616
  brandStrength: 0.06202159
  brandColors:
    - '#16061F'
    - '#6F3176'
    - '#D875E1'
    - '#FFFCFF'
    - '#884AFF'
  rhythmicContrast: 0.3595418
typography_spectrum: 0.5088689
name: JustSayNoToHPS
